# Generated by Django 4.0.3 on 2022-05-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
    ]
